"""Orchestration for the full offline conformal Value-at-Risk workflow."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from conformal_var_risk.config import load_config
from conformal_var_risk.data.daily_panel import build_daily_log_return_panel
from conformal_var_risk.data.raw_cache import load_raw_minute_bars
from conformal_var_risk.data.realized_variance import (
    build_daily_realized_variance_panel,
)
from conformal_var_risk.evaluation.backtest import run_backtest
from conformal_var_risk.evaluation.metrics import compute_summary_metrics
from conformal_var_risk.features.feature_builder import build_feature_table
from conformal_var_risk.models.registry import build_model_factories


@dataclass(frozen=True)
class PipelineArtifacts:
    """Filesystem outputs generated by one pipeline run."""

    daily_returns_path: Path
    realized_variance_path: Path
    feature_table_path: Path
    backtest_results_path: Path
    metrics_path: Path


def run_pipeline(config_path: Path) -> PipelineArtifacts:
    """Execute offline preprocessing, backtesting, and metric generation.

    Parameters
    ----------
    config_path
        Path to the project TOML config.

    Returns
    -------
    PipelineArtifacts
        Paths to generated parquet artifacts.
    """
    resolved_config_path = config_path.resolve()
    config = load_config(resolved_config_path)
    project_root = resolved_config_path.parent

    # All derived artifacts land under the configured output folder.
    output_dir = project_root / config.run.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    daily_returns_path = output_dir / "daily_returns.parquet"
    realized_variance_path = output_dir / "daily_realized_variance.parquet"
    feature_table_path = output_dir / "feature_table.parquet"
    backtest_results_path = output_dir / "backtest_results.parquet"
    metrics_path = output_dir / "summary_metrics.parquet"

    # Stage 1: load and validate offline raw minute bars.
    raw_minute_bars = load_raw_minute_bars(
        raw_dir=project_root / config.raw_data.raw_dir,
        file_pattern=config.raw_data.file_pattern,
        required_symbols=config.portfolio.symbols,
        start_date=config.run.start_date,
        end_date=config.run.end_date,
    )

    # Stage 2: build daily return and realized-variance panels from the same raw input.
    daily_returns = build_daily_log_return_panel(
        minute_bars=raw_minute_bars,
        symbols=config.portfolio.symbols,
    )
    daily_returns.to_parquet(daily_returns_path)

    daily_realized_variance = build_daily_realized_variance_panel(
        minute_bars=raw_minute_bars,
        symbols=config.portfolio.symbols,
    )
    daily_realized_variance.to_parquet(realized_variance_path)

    # Features need return and RV rows on the same calendar dates.
    aligned_realized_variance = daily_realized_variance.reindex(daily_returns.index)

    feature_table = build_feature_table(
        daily_returns=daily_returns,
        realized_variance=aligned_realized_variance,
        include_realized_return_volatility_5d=config.features.include_realized_return_volatility_5d,
    )
    feature_table.to_parquet(feature_table_path, index=False)

    # Stage 3: walk-forward backtest and period summaries.
    model_factories = build_model_factories(config=config)
    backtest_results = run_backtest(
        returns_by_asset=daily_returns,
        alphas=config.backtest.alphas,
        calibration_window=config.backtest.calibration_window,
        model_factories=model_factories,
    )
    backtest_results.to_parquet(backtest_results_path, index=False)

    metrics_frame = compute_summary_metrics(
        backtest_results=backtest_results,
        evaluation_config=config.evaluation,
    )
    metrics_frame.to_parquet(metrics_path, index=False)

    return PipelineArtifacts(
        daily_returns_path=daily_returns_path,
        realized_variance_path=realized_variance_path,
        feature_table_path=feature_table_path,
        backtest_results_path=backtest_results_path,
        metrics_path=metrics_path,
    )
